2024-05-21 00:23:31,505 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-21 00:23:31,505 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Configure stats pid to 952313
2024-05-21 00:23:31,505 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Loading settings from /home/jeehyun/.config/wandb/settings
2024-05-21 00:23:31,505 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Loading settings from /home/jeehyun/coursework/DL/MeOw-LO/wandb/settings
2024-05-21 00:23:31,505 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train.py', 'program_abspath': '/home/jeehyun/coursework/DL/MeOw-LO/train.py', 'program': '/home/jeehyun/coursework/DL/MeOw-LO/train.py'}
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_init.py:_log_setup():520] Logging user logs to /home/jeehyun/coursework/DL/MeOw-LO/wandb/run-20240521_002331-i3w5zter/logs/debug.log
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_init.py:_log_setup():521] Logging internal logs to /home/jeehyun/coursework/DL/MeOw-LO/wandb/run-20240521_002331-i3w5zter/logs/debug-internal.log
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_init.py:init():560] calling init triggers
2024-05-21 00:23:31,506 INFO    MainThread:952313 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'directory': '/data/etc/molo/CAT_train', 'test_directory': '/data/etc/molo/CAT_val', 'batch_size': 16, 'epochs': 10, 'lr': 0.0001, 'output_dir': '/home/jeehyun/coursework/DL/MeOw-LO/output'}
2024-05-21 00:23:31,507 INFO    MainThread:952313 [wandb_init.py:init():610] starting backend
2024-05-21 00:23:31,507 INFO    MainThread:952313 [wandb_init.py:init():614] setting up manager
2024-05-21 00:23:31,515 INFO    MainThread:952313 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-05-21 00:23:31,517 INFO    MainThread:952313 [wandb_init.py:init():622] backend started and connected
2024-05-21 00:23:31,533 INFO    MainThread:952313 [wandb_init.py:init():711] updated telemetry
2024-05-21 00:23:31,543 INFO    MainThread:952313 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-21 00:23:31,993 ERROR   MainThread:952313 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-21 00:23:31,993 ERROR   MainThread:952313 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/home/jeehyun/.miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/jeehyun/.miniconda3/envs/dl/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-21 00:23:33,156 WARNING MsgRouterThr:952313 [router.py:message_loop():77] message_loop has been closed
